#!/usr/bin/env bash
# Resolve every (projectID, fileID) entry in a CurseForge modpack manifest.json
# into a fetchurl-ready Nix attrset list. Output goes to arkana-mods.nix.
#
# Run once from the host (not inside a Nix sandbox) when bumping the Arkana
# version, then commit the regenerated arkana-mods.nix.
#
# Why a generated file instead of fetching at eval-time:
# - Nix sandboxes builds; fetchurl needs URL+hash known up-front.
# - cfwidget rate-limits + occasionally errors; resolving 259 mods at every
#   eval would be flaky.
#
# Deps (run on host): bash, curl, jq, nix-prefetch-url.

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "usage: $0 <path/to/manifest.json> <path/to/out.nix>" >&2
  exit 2
fi

MANIFEST="$1"
OUT="$2"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

resolve_file() {
  # cfwidget proxies CurseForge metadata. Returns name + filesize + version
  # info for a project; we filter the embedded files[] by fileID.
  local projectID="$1" fileID="$2"
  local meta
  for attempt in 1 2 3; do
    meta="$(curl -sfL --max-time 30 "https://api.cfwidget.com/${projectID}?version=${fileID}" || true)"
    if [[ -n "$meta" ]] && echo "$meta" | jq -e --argjson id "$fileID" '.files[]? | select(.id == $id)' >/dev/null; then
      echo "$meta" | jq -r --argjson id "$fileID" '.files[] | select(.id == $id) | .name'
      return 0
    fi
    sleep $((attempt * 2))
  done
  echo "ERROR: failed to resolve projectID=${projectID} fileID=${fileID} after 3 attempts" >&2
  return 1
}

mediafilez_url() {
  # Mediafilez splits the fileID into a 4-digit prefix and a remainder so
  # `printf %.0f` (truncate) on fileID/1000 gives the prefix component.
  local fileID="$1" filename="$2"
  local prefix=$(( fileID / 1000 ))
  local suffix=$(( fileID % 1000 ))
  # Mediafilez's S3 backend signs URLs against the *encoded* object key, so
  # `+` and ` ` in the filename must percent-encode (raw `+` 403s, raw space
  # 404s). jq's @uri encodes too aggressively (it touches `-`, `_`, `.`),
  # which mediafilez also 404s on, so we hand-encode just the chars we've
  # actually seen break in CurseForge filenames: space, plus, and brackets.
  # curl 8.x rejects literal `[`/`]` ("bad range in URL position N",
  # IPv6-zone parser); mediafilez serves the %5B/%5D form fine.
  local encoded="$filename"
  encoded="${encoded// /%20}"
  encoded="${encoded//+/%2B}"
  encoded="${encoded//\[/%5B}"
  encoded="${encoded//\]/%5D}"
  printf 'https://mediafilez.forgecdn.net/files/%d/%d/%s' "$prefix" "$suffix" "$encoded"
}

total=$(jq '.files | length' "$MANIFEST")
{
  echo "# AUTO-GENERATED by pkgs/create-arkana-aeronautics-server/generate-arkana-mods.sh"
  echo "# Source: Create: Arkana manifest.json (${total} entries)"
  echo "{ fetchurl }:"
  echo "["
} > "$OUT"

i=0
jq -c '.files[]' "$MANIFEST" | while read -r entry; do
  i=$((i+1))
  projectID=$(echo "$entry" | jq -r '.projectID')
  fileID=$(echo "$entry" | jq -r '.fileID')
  required=$(echo "$entry" | jq -r '.required')

  echo "[$i/$total] resolving project=$projectID file=$fileID..." >&2

  filename="$(resolve_file "$projectID" "$fileID")" || continue
  url="$(mediafilez_url "$fileID" "$filename")"

  # Nix store paths reject `%`, `'`, and other shell-fragile chars in
  # filenames. Strip apostrophes and replace any remaining illegal char
  # with `_`; on-disk store name diverges from the original filename in
  # rare cases (~0.5% of mods) but the `name` field in fetchurl tolerates
  # the rename and the install step uses the original name as the basename.
  storeName="$(printf '%s' "$filename" | tr -d "'" | sed 's/[^A-Za-z0-9._+-]/_/g')"

  hash="$(nix-prefetch-url --type sha256 --name "$storeName" "$url" 2>/dev/null || true)"
  if [[ -z "$hash" ]]; then
    echo "  WARN: prefetch failed for $url" >&2
    continue
  fi

  # `name` must be a valid Nix store-path name (storeName, sanitized); the
  # consumer-side `filename` is the original CurseForge name and is used
  # when copying into mods/. Escape backslashes and double-quotes for the
  # Nix string literal — apostrophes are already stripped from storeName
  # but may survive in the original filename.
  nixFilename="$(printf '%s' "$filename" | sed 's/\\/\\\\/g; s/"/\\"/g')"
  cat >> "$OUT" <<EOF
  {
    projectID = ${projectID};
    fileID    = ${fileID};
    required  = ${required};
    filename  = "${nixFilename}";
    jar = fetchurl {
      url    = "${url}";
      name   = "${storeName}";
      sha256 = "${hash}";
    };
  }
EOF
done

echo "]" >> "$OUT"
echo "Wrote $OUT" >&2
