keys:
  - &admin_ali age1rne0eqj5jfqahm5s5mmp3u0v97xm0lvwm2ghtjlv4p7m0l78tq5stgjtu4
  - &ali_personal age1efmxs2w78yw0knq7hvzxjsanphqgrx2mj5p5grkye590yq4rjexs5zvvzg
  - &server_ali-desktop age1h3hqvnnyey9sgnkssz0l35a795fk9msx9ft6wj30ejepyah609fqlg70lv
  - &server_home-k8s-master-1 age19z7a82p4sv7c2f739842nf943kwqkvawj6nq2hpfvvr0564dgcdsdtjrca
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_ali
      - *ali_personal
  - path_regex: secrets/ali-desktop/[^/]+\.(yaml|json|env|ini|bin)$
    key_groups:
    - age:
      - *admin_ali
      - *ali_personal
      - *server_ali-desktop
  - path_regex: secrets/home-k8s-master-1/[^/]+\.(yaml|json|env|ini|bin)$
    key_groups:
    - age:
      - *admin_ali
      - *ali_personal
      - *server_home-k8s-master-1
