{ pkgs }: {
  "-- -" = "cd -";
  ".." = "cd ..";
  "..." = "cd ../..";
  "...." = "cd ../../..";
  "....." = "cd ../../../..";
  "cdd" = "cd ~/Downloads/";
  "cdg" = "cd ~/git/";
  "gb" = "go build";
  "gbw" = "watchexec --clear --exts go -- go build";
  "gtw" = "watchexec --clear --exts go -- go test";
  "cdot" = "cd ~/.local/share/chezmoi";
  "gc" = "${pkgs.callPackage ../pkgs/git-clean { inherit pkgs; }}/bin/git-clean";
  "j" = "just";
  "key" = "ssh-add ~/.ssh/ssh_keys/id_bashton_alan";
  "keyaur" = "ssh-add ~/.ssh/ssh_keys/id_aur";
  "keyb" = "ssh-add ~/.ssh/ssh_keys/id_bashton";
  "keycl" = "ssh-add -D";
  "keyk" = "ssh-add ~/.ssh/ssh_keys/id_krystal";
  "keyp" = "ssh-add ~/.ssh/ssh_keys/id_personal";
  "keypa" = "ssh-add ~/.ssh/ssh_keys/id_alan-aws";
  "keypo" = "ssh-add ~/.ssh/ssh_keys/id_personal_old";
  "kmse" = "export EYAML_CONFIG=$PWD/.kms-eyaml.yaml";
  "ll" = "${pkgs.eza}/bin/eza -l --grid --git";
  "ls" = "${pkgs.eza}/bin/eza";
  "lt" = "${pkgs.eza}/bin/eza --tree --git --long";
  "nfr" = "nix run .";
  "nfu" = "nix flake update";
  "nsg" = "nix store gc";
  "nsgo" = "nix store gc && nix store optimise";
  "nso" = "nix store optimise";
  "pwhash" = "python -c \"import crypt,getpass; print(crypt.crypt(getpass.getpass(), crypt.mksalt(crypt.METHOD_SHA512)))\"";
  "vi" = "nvim";
  "vim" = "nvim";
  "vpn" = "sudo openconnect --config ~/.config/openconnect/config";
}
