apiVersion: v1
kind: Namespace
metadata:
  name: cilium
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart: cilium
  version: '1.16.4'
  repo: https://helm.cilium.io/
  # releaseName: cilium
  targetNamespace: cilium
  valuesContent: |-
    # autoDirectNodeRoutes: true
    # hostLegacyRouting: false
    k8sServiceHost: 192.168.1.251
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    # tunnel: disabled

    # bqf:
    #   masquerade: true

    ipam:
      # mode: kubernetes
      operator:
        clusterPoolIPv4PodCIDRList: "10.42.0.0/16"

    nodePort:
      enabled: true

    # -- Roll out cilium agent pods automatically when configmap is updated.
    rollOutCiliumPods: true

    # # -- Enable installation of PodCIDR routes between worker
    # # nodes if worker nodes share a common L2 network segment.
    # autoDirectNodeRoutes: true

    # # -- Enable skipping of PodCIDR routes between worker
    # # nodes if the worker nodes are in a different L2 network segment.
    # directRoutingSkipUnreachable: true

    # -- Enables IPv4 BIG TCP support which increases maximum IPv4 GSO/GRO limits for nodes and pods
    # enableIPv4BIGTCP: true

    # # -- Enables IPv6 BIG TCP support which increases maximum IPv6 GSO/GRO limits for nodes and pods
    # enableIPv6BIGTCP: false

    # -- Enable bandwidth manager to optimize TCP and UDP workloads and allow
    # for rate-limiting traffic from individual Pods with EDT (Earliest Departure
    # Time) through the "kubernetes.io/egress-bandwidth" Pod annotation.
    bandwidthManager:
      # -- Enable bandwidth manager infrastructure (also prerequirement for BBR)
      enabled: true
      # -- Activate BBR TCP congestion control for Pods
      bbr: true

    # bpf:
    #   # -- (string) Mode for Pod devices for the core datapath (veth, netkit, netkit-l2, lb-only)
    #   # @default -- `veth`
    #   datapathMode: netkit

    envoyConfig:
      # -- Enable CiliumEnvoyConfig CRD
      # CiliumEnvoyConfig CRD can also be implicitly enabled by other options.
      enabled: true
      # -- Interval in which an attempt is made to reconcile failed EnvoyConfigs. If the duration is zero, the retry is deactivated.
      retryInterval: 15s
      # -- SecretsNamespace is the namespace in which envoy SDS will retrieve secrets from.
      secretsNamespace:
        # -- Create secrets namespace for CiliumEnvoyConfig CRDs.
        create: true
        # -- The name of the secret namespace to which Cilium agents are given read access.
        name: cilium-secrets

    l2announcements:
      enabled: true

    loadBalancerIPs:
      enabled: true

    k8sClientRateLimit:
      burst: 100
      qps: 50

