lambda_name := "my-lambda"
region := "eu-west-1"

# Build the Lambda package with Nix
build:
    nix build

# Build the Lambda deployment zip
zip:
    nix build .#zip

# Run checks (tests)
check:
    nix flake check

# Run tests
test:
    node --test test/

# Invoke the Lambda handler locally for testing
invoke payload='{"name": "world"}':
    node -e "const h = require('./src/handler'); h.handler({{ payload }}).then(r => console.log(JSON.stringify(r)))"

# Deploy zip to Lambda
deploy-zip: zip
    aws lambda update-function-code \
      --function-name {{ lambda_name }} \
      --zip-file fileb://result/my-lambda.zip \
      --region {{ region }}
