# opencodeLocalLLM read via `args ... or` rather than a named formal arg: the
# module system resolves named args through _module.args and errors when the
# specialArg is absent, ignoring lambda defaults.
{ pkgs, lib, inputs, ... } @ args:
let
  opencodeLocalLLM = args.opencodeLocalLLM or true;

  mandates = import ../shared-mandates.nix;
  inherit (mandates) gitStrategy workStyle;

  # Hosts without a local llama endpoint (opencodeLocalLLM = false via
  # home-manager.extraSpecialArgs) fall back to opencode's built-in
  # github-copilot provider, which needs no provider block in config.json
  # (auth via `opencode auth login github-copilot`).
  defaultModel =
    if opencodeLocalLLM then "local/qwen3-32b"
    else "github-copilot/claude-sonnet-4.5";

  cavemanPkg = pkgs.caveman;
  cavememPkg = pkgs.cavemem;

  mkProvider = { baseURL, models }:
    { options = { inherit baseURL; }; inherit models; };

  mkModel = {
    name,
    toolCall ? true,
    reasoning ? true,
    attachment ? true,
    temperature ? true,
    contextLimit,
    outputLimit,
  }: {
    inherit name attachment reasoning temperature;
    tool_call = toolCall;
    limit = { context = contextLimit; output = outputLimit; };
  };

  stripClaudeFrontmatter = file:
    let
      raw = builtins.readFile file;
      lines = lib.splitString "\n" raw;
      inFrontmatter = builtins.head lines == "---";
      body =
        if !inFrontmatter then raw
        else
          let
            rest = builtins.tail lines;
            endIdx = lib.lists.findFirstIndex (l: l == "---") null rest;
          in
            if endIdx == null then raw
            else lib.concatStringsSep "\n" (lib.drop (endIdx + 1) rest);
    in lib.trimWith { start = true; end = false; } body;

  mkOpencodeAgent = { file, description, model ? defaultModel, mode ? "subagent", extraBody ? "" }:
    ''
      ---
      description: "${description}"
      mode: ${mode}
      model: ${model}
      ---

      ${stripClaudeFrontmatter file}${lib.optionalString (extraBody != "") "\n${extraBody}"}
    '';

  cavemanCommandFiles = lib.filterAttrs (n: v: v == "regular" && lib.hasSuffix ".md" n)
    (builtins.readDir "${cavemanPkg}/opencode-commands");

  cavemanCommandConfigs = lib.mapAttrs' (name: _:
    lib.nameValuePair "opencode/commands/${name}" {
      source = "${cavemanPkg}/opencode-commands/${name}";
    }
  ) cavemanCommandFiles;

  cavememCli = "${cavememPkg}/bin/cavemem";

  cavememPluginJS = ''
    // AUTO-GENERATED by nix home-manager. Do not edit by hand.
    // Re-run home-manager switch to refresh.
    import { spawn } from 'node:child_process';

    const CLI = ${builtins.toJSON cavememCli};

    const callArgs = new Map();

    function runHook(event, payload) {
      try {
        const child = spawn(CLI, ['hook', 'run', event, '--ide', 'opencode'], {
          stdio: ['pipe', 'ignore', 'ignore'],
          detached: true,
        });
        child.on('error', () => {});
        child.stdin.on('error', () => {});
        child.stdin.end(JSON.stringify(payload));
        child.unref();
      } catch (_e) {}
    }

    export const cavemem = async () => ({
      'session.created': async (input) => {
        runHook('session-start', { session_id: input?.sessionID ?? 'unknown', ide: 'opencode' });
      },
      'session.idle': async (input) => {
        runHook('stop', { session_id: input?.sessionID ?? 'unknown', ide: 'opencode' });
      },
      'tool.execute.before': async (input, output) => {
        if (input?.callID) callArgs.set(input.callID, output?.args);
      },
      'tool.execute.after': async (input, output) => {
        const args = input?.callID ? callArgs.get(input.callID) : undefined;
        if (input?.callID) callArgs.delete(input.callID);
        runHook('post-tool-use', {
          session_id: input?.sessionID ?? 'unknown',
          ide: 'opencode',
          tool_name: input?.tool ?? 'unknown',
          tool_input: args ?? null,
          tool_response: output?.output ?? output?.title ?? null,
        });
      },
    });
  '';

in {
  xdg.configFile = {
    # Main opencode config
    "opencode/config.json".text = builtins.toJSON {
      "$schema" = "https://opencode.ai/config.json";

      provider = lib.optionalAttrs opencodeLocalLLM {
        local = mkProvider {
          baseURL = "http://localhost:8080/v1";
          models.qwen3-32b = mkModel {
            name = "Qwen3-32B";
            contextLimit = 122880;
            outputLimit = 16384;
          };
        };
      };

      model = defaultModel;
      small_model = defaultModel;

      instructions = [
        "~/.config/opencode/instructions/git-strategy.md"
        "~/.config/opencode/instructions/work-style.md"
        "~/.config/opencode/instructions/tool-use.md"
      ];

      # Only lightweight MCPs — heavy ones replaced by lazy-loaded skills
      mcp = {
        context7 = {
          type = "local";
          command = [ "${pkgs.master.context7-mcp}/bin/context7-mcp" ];
        };
        nixos = {
          type = "local";
          command = [ "${pkgs.master.mcp-nixos}/bin/mcp-nixos" ];
        };
        cavemem = {
          type = "local";
          command = [ cavememCli "mcp" ];
        };
      };

      permission = {
        read = "allow";
        edit = "allow";
        glob = "allow";
        grep = "allow";
        webfetch = "allow";
        bash = "allow";
        task = "allow";
        skill = { "*" = "allow"; };
      };
    };

    # TUI config (notifications)
    "opencode/tui.json".text = builtins.toJSON {
      attention = {
        enabled = true;
        notifications = true;
        sound = true;
        volume = 0.4;
      };
    };

    # Instruction files (mandates)
    "opencode/instructions/git-strategy.md".text = gitStrategy;
    "opencode/instructions/work-style.md".text = workStyle;
    "opencode/instructions/tool-use.md".text = ''
      # Tool Use (system instruction)

      You have access to tools provided by opencode. Always prefer using tools
      over asking the user to run commands. When you need to read files, search
      code, edit files, or run commands, use the appropriate tool.

      When calling tools, provide all required arguments. For bash commands,
      prefer specific commands over interactive ones.

      When multiple independent tool calls would help, make them in parallel
      when the tool supports it.
    '';

    # Custom agents
    "opencode/agents/aws-iam-debugger.md".text = mkOpencodeAgent {
      file = ../claude-code/agents/aws-iam-debugger.md;
      description = "Debug AWS IAM permission errors, access denied messages, or authorization failures";
    };
    "opencode/agents/git-commit-generator.md".text = mkOpencodeAgent {
      file = ../claude-code/agents/git-commit-generator.md;
      description = "Generate atomic git commit messages following conventional commit format";
      extraBody = gitStrategy;
    };
    "opencode/agents/pr-creator.md".text = mkOpencodeAgent {
      file = ../claude-code/agents/pr-creator.md;
      description = "Create GitHub pull requests with rebasing, quality gates, and clear descriptions";
      extraBody = gitStrategy;
    };

    # Caveman opencode plugin
    "opencode/plugins/caveman/plugin.js".source = "${cavemanPkg}/opencode-plugin/plugin.js";
    "opencode/plugins/caveman/package.json".source = "${cavemanPkg}/opencode-plugin/package.json";
    "opencode/plugins/caveman/caveman-config.cjs".source = "${cavemanPkg}/opencode-plugin/caveman-config.cjs";

    # Cavemem opencode plugin
    "opencode/plugins/cavemem.js".text = cavememPluginJS;

    # Skills shared with Claude Code, from home/skills/
    # (flake.lib.skills). Linked as whole directories, not single files, so
    # each family's bundled children (languages/*.md, per-tool guides) come
    # along — that is where the detail lives, loaded on demand rather than
    # sitting in baseline context.
    #
    # These SKILL.md files use agentskills.io spec frontmatter only, which is
    # what makes them usable from here as well as from Claude Code. The infra
    # family replaced the former inline github / kubernetes / terraform skills,
    # which duplicated the same CLI guidance.

  }
  // cavemanCommandConfigs
  // lib.mapAttrs' (
    name: path: lib.nameValuePair "opencode/skills/${name}" { source = path; }
  ) inputs.self.lib.skills;
}
