# AUTO-GENERATED by pkgs/beatsaber-mods/generate-mods.py
# Source: BeatMods API, gameVersion=1.44.1 (17 mods incl. dependencies)
{ fetchurl }:
[
  {
    name     = "BeatSaberMarkupLanguage";
    modId    = 96;
    version  = "1.14.1";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/46149d03f8549e07f2c88fefde4337b2.zip";
      name   = "BeatSaberMarkupLanguage-1.14.1.zip";
      sha256 = "816613459853955e2b7c02123ed42f8e5bdbd946cc774fd5fcc4e80a6a09120a";
    };
  }
  {
    name     = "BeatSaverDownloader";
    modId    = 5;
    version  = "6.0.7";
    category = "essential";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/a740c6e68a9b5d1dfda3cc8e81f7cf06.zip";
      name   = "BeatSaverDownloader-6.0.7.zip";
      sha256 = "4108b11eae11d09f8c4e838dde1dc36108f1f3fd4fff31b951e7c551fa59f5f1";
    };
  }
  {
    name     = "BeatSaverSharp";
    modId    = 101;
    version  = "3.4.5";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/be37e13e93d9ac7da4efbdc3f514fa8f.zip";
      name   = "BeatSaverSharp-3.4.5.zip";
      sha256 = "f5f37b27438e9b2fa1d9fbdf51a4f015f44ae04979cbdd9b90f6ae18583a6911";
    };
  }
  {
    name     = "BS Utils";
    modId    = 22;
    version  = "1.14.3";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/918d13ac2821a3a17b2819f8861453e9.zip";
      name   = "BS-Utils-1.14.3.zip";
      sha256 = "b450fa4561da5b5ad834a3dcf6f127c2d73e5f971aa6c986514a6b185d68edfe";
    };
  }
  {
    name     = "BSIPA";
    modId    = 1;
    version  = "4.3.7";
    category = "core";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/947774ef1010ff809ae05e345e269a90.zip";
      name   = "BSIPA-4.3.7.zip";
      sha256 = "899b8a1dda91935bd5c19a211fa48e44e32f7be9ab82b6fc796709c753b7b2bc";
    };
  }
  {
    name     = "Enhancements";
    modId    = 93;
    version  = "3.0.20";
    category = "tweaks";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/638a847d32d8e510a12b929c578057fc.zip";
      name   = "Enhancements-3.0.20.zip";
      sha256 = "5c1fc097ad6773ee76d87ab15e861dac769de948857c8185f6d3716c9df871e2";
    };
  }
  {
    name     = "GottaGoFast";
    modId    = 279;
    version  = "0.2.5";
    category = "tweaks";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/05975004e449731788da1fd8206fb52e.zip";
      name   = "GottaGoFast-0.2.5.zip";
      sha256 = "eec2074216d93f331faba32153d98bd4f3dcfa9716e6e7091c1e874f0b91c3ba";
    };
  }
  {
    name     = "Ini Parser";
    modId    = 20;
    version  = "2.5.9";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/5df74ad1c6b120fecdc615dd55f15b88.zip";
      name   = "Ini-Parser-2.5.9.zip";
      sha256 = "b761293bea73ff3cb9998f404594aade617638aba4318203320189baf3449ff1";
    };
  }
  {
    name     = "MenuSelector";
    modId    = 365;
    version  = "1.0.0";
    category = "cosmetic";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/bf0d19076968f64be75a4e0d3280031f.zip";
      name   = "MenuSelector-1.0.0.zip";
      sha256 = "41d66f6afea4715f5fd78f64df5030de9a9de99d97120b8061f38b20280f52ac";
    };
  }
  {
    name     = "protobuf-net";
    modId    = 194;
    version  = "3.0.102";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/1f55ae4b80b747b5f03fa18337ead864.zip";
      name   = "protobuf-net-3.0.102.zip";
      sha256 = "8bf4a361038172eab2c0c2e6737773d6c9a47fc6504a97304a35f697d5166414";
    };
  }
  {
    name     = "RandomSongPlayer";
    modId    = 95;
    version  = "2.0.3";
    category = "gameplay";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/b788ce8145e80d326039e909e52bf488.zip";
      name   = "RandomSongPlayer-2.0.3.zip";
      sha256 = "7d0924e7077ef7b65eb6358526dd29c8c67480179bd394584d3051f471dc3df3";
    };
  }
  {
    name     = "ScoreSaberSharp";
    modId    = 102;
    version  = "0.1.0";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/8713168c598577ee7c73fa3cf0e26f5c.zip";
      name   = "ScoreSaberSharp-0.1.0.zip";
      sha256 = "7f30be996f8f0e997f2d848e34de1d03ef6dc744ffc32d3fe505881ca22c6cd3";
    };
  }
  {
    name     = "SiraUtil";
    modId    = 130;
    version  = "3.3.1";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/ae14f7d3192a919d5d996c802fbde037.zip";
      name   = "SiraUtil-3.3.1.zip";
      sha256 = "2253e5c31324e1e01b23480acba5ceee6b67eb8f16a079f58bc2f6ce7b12051f";
    };
  }
  {
    name     = "SongCore";
    modId    = 58;
    version  = "3.16.0";
    category = "core";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/0af9c0a03074c17ca15c1b667a0e30c8.zip";
      name   = "SongCore-3.16.0.zip";
      sha256 = "f9be5d66426d795c6c8af2a4da0150a298d2d6a65fbabcab316d379088a40019";
    };
  }
  {
    name     = "SongDetailsCache";
    modId    = 192;
    version  = "1.4.0";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/e1167b64cd3eff7e3651ec2dbbe50d81.zip";
      name   = "SongDetailsCache-1.4.0.zip";
      sha256 = "6ccc816dd40752b46d5e7e1cfb41e5af9d915d1a032be51ce1e52fb154daa28c";
    };
  }
  {
    name     = "System.IO.Compression";
    modId    = 304;
    version  = "4.6.57";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/a4e9e26f61967e56168e08eecb01ab88.zip";
      name   = "System.IO.Compression-4.6.57.zip";
      sha256 = "9067ddaf52c077f38a27ace6180a8134ceaaf1ecba752d08de81b4cc0c13aa43";
    };
  }
  {
    name     = "System.IO.Compression.FileSystem";
    modId    = 303;
    version  = "4.7.3056";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/e19f6fd395d54de7bfcbbbe3084dea28.zip";
      name   = "System.IO.Compression.FileSystem-4.7.3056.zip";
      sha256 = "1b6f7a33a69980344717a37240ed80b022903a52968d4968f307cf754e3a03f7";
    };
  }
]
