# AUTO-GENERATED by pkgs/beatsaber-mods/generate-mods.py
# Source: BeatMods API, gameVersion=1.40.8 (39 mods incl. dependencies)
{ fetchurl }:
[
  {
    name     = "AssetBundleLoadingTools";
    modId    = 306;
    version  = "1.1.10";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/9420b5ad75c00df8a17ba7170d241344.zip";
      name   = "AssetBundleLoadingTools-1.1.10.zip";
      sha256 = "25ded8bb1d0db2dd8a4d8bc7d1e1c9cfdf3a99a4a424145560bbd23508725ab9";
    };
  }
  {
    name     = "BeatLeader";
    modId    = 268;
    version  = "0.9.33-1.40.2";
    category = "other";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/26244ec8e341e9c96f59a67c39875cbe.zip";
      name   = "BeatLeader-0.9.33-1.40.2.zip";
      sha256 = "c94d894fae79d5b761ac8c58e5c5c6f8b3bf52588981ff694b3f97acb9ae7fd0";
    };
  }
  {
    name     = "BeatSaberMarkupLanguage";
    modId    = 96;
    version  = "1.12.5";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/ce406862c55fdc1b572f99f8e4dbd1eb.zip";
      name   = "BeatSaberMarkupLanguage-1.12.5.zip";
      sha256 = "2e34a76e7b5750ce617c0df5adc995745cb9ab0d71dde9e0076b2ea592ebb7bd";
    };
  }
  {
    name     = "BeatSaberPlaylistsLib";
    modId    = 176;
    version  = "1.7.2";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/a3418b75ed7294a3856f3eca12bbd672.zip";
      name   = "BeatSaberPlaylistsLib-1.7.2.zip";
      sha256 = "dfb26cf90cb73834c405727418c0121d8546cad0403abd35a09437dab766bd32";
    };
  }
  {
    name     = "BeatSaverDownloader";
    modId    = 5;
    version  = "6.0.7";
    category = "essential";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/a740c6e68a9b5d1dfda3cc8e81f7cf06.zip";
      name   = "BeatSaverDownloader-6.0.7.zip";
      sha256 = "4108b11eae11d09f8c4e838dde1dc36108f1f3fd4fff31b951e7c551fa59f5f1";
    };
  }
  {
    name     = "BeatSaverSharp";
    modId    = 101;
    version  = "3.4.5";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/be37e13e93d9ac7da4efbdc3f514fa8f.zip";
      name   = "BeatSaverSharp-3.4.5.zip";
      sha256 = "f5f37b27438e9b2fa1d9fbdf51a4f015f44ae04979cbdd9b90f6ae18583a6911";
    };
  }
  {
    name     = "BeatSaverUpdater";
    modId    = 254;
    version  = "1.2.11";
    category = "essential";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/d9ea8dd0cbaac66cbb02fa59a548e42b.zip";
      name   = "BeatSaverUpdater-1.2.11.zip";
      sha256 = "6237da05cbc044e99211cb0e569c917fe61bb0da25e42c61a6d438371548ebba";
    };
  }
  {
    name     = "BetterSongList";
    modId    = 226;
    version  = "0.4.2";
    category = "ui";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/827d315b4e65bcaba816aa2dfd76c10f.zip";
      name   = "BetterSongList-0.4.2.zip";
      sha256 = "4a05b19cab06bc4c0b81a2e2b9515e54b306ee7d20e0e8c28fd85bbef03e965a";
    };
  }
  {
    name     = "BetterSongSearch";
    modId    = 225;
    version  = "0.8.1";
    category = "tweaks";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/edb61862ace9b2b0f595a34c0a96f60f.zip";
      name   = "BetterSongSearch-0.8.1.zip";
      sha256 = "e596cc671742d4053bd9c1db7fafe67a7d2e5de79d4c37b449f335b378571b4d";
    };
  }
  {
    name     = "BS Utils";
    modId    = 22;
    version  = "1.14.2";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/b8245da532d16147d15daab5fc735c46.zip";
      name   = "BS-Utils-1.14.2.zip";
      sha256 = "99f98c5d5ac2488726d611e6652961015276475f7aeb96cd68ee805098ae4e6b";
    };
  }
  {
    name     = "BSIPA";
    modId    = 1;
    version  = "4.3.6";
    category = "core";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/22ddb9499bf8b308ea30d2b555172baf.zip";
      name   = "BSIPA-4.3.6.zip";
      sha256 = "fbd6eafb662d63032b06dc964b6cf84e8b5dd5566527131d8c0b8ea63280043a";
    };
  }
  {
    name     = "Camera2";
    modId    = 186;
    version  = "0.6.118";
    category = "essential";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/536c43edf37e4d6ee4e6fd38c2e36e87.zip";
      name   = "Camera2-0.6.118.zip";
      sha256 = "caa5684509b30d9d72b50bd8624b110a75b04a27ac1ec754633d551a9e500b7a";
    };
  }
  {
    name     = "CameraUtils";
    modId    = 265;
    version  = "1.0.7";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/471d40a9a5c951f4e7f5520096f00bdb.zip";
      name   = "CameraUtils-1.0.7.zip";
      sha256 = "5d0f3d1473451bde5b1567b2f1376e28e07a48cdf70aefa66a38ae63478e67c1";
    };
  }
  {
    name     = "Chroma";
    modId    = 132;
    version  = "2.9.20+1.40.3";
    category = "lighting";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/740e84fbcacf14d6cb738562bcc641ec.zip";
      name   = "Chroma-2.9.20+1.40.3.zip";
      sha256 = "43bc9faf977b5f0bf0eac9c1381efb820e3f799ddcf65c1a014f06feb7040dd1";
    };
  }
  {
    name     = "CustomJSONData";
    modId    = 129;
    version  = "2.6.8+1.40.0";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/fed31638bbb678580ef760ec83cfd486.zip";
      name   = "CustomJSONData-2.6.8+1.40.0.zip";
      sha256 = "30555c77485d2837bd294608fe4e23c34415b89413997be67a6150318090b216";
    };
  }
  {
    name     = "CustomSabersLite";
    modId    = 307;
    version  = "1.0.3";
    category = "cosmetic";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/16d02b5a4e1feeb8ab9b92c984b77639.zip";
      name   = "CustomSabersLite-1.0.3.zip";
      sha256 = "75eb5670c31843bdebcbb99a09e28af6485390849856473544f17574dbb40276";
    };
  }
  {
    name     = "Enhancements";
    modId    = 93;
    version  = "3.0.18";
    category = "tweaks";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/e1be3c62cac95e98b7e4e91d5b52090d.zip";
      name   = "Enhancements-3.0.18.zip";
      sha256 = "919c310d75ea4ed0630d34fdee2c0822b0979837fe939971b5837ae43fc06050";
    };
  }
  {
    name     = "GottaGoFast";
    modId    = 279;
    version  = "0.2.4";
    category = "tweaks";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/cc46b5978f95cb0b25c2f47d4a4d2796.zip";
      name   = "GottaGoFast-0.2.4.zip";
      sha256 = "8d0a283bfc0b7ef7c4062e5b062c4d09c17671c5d47628bca6d35f525a348212";
    };
  }
  {
    name     = "Heck";
    modId    = 338;
    version  = "1.7.14+1.40.3";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/5977d5b8a4db74b438e552da18532b7f.zip";
      name   = "Heck-1.7.14+1.40.3.zip";
      sha256 = "73de93ad7ac8028b37d24112565ed2dd58d19558a3ce7033848be8f1e1991615";
    };
  }
  {
    name     = "HitScoreVisualizer";
    modId    = 40;
    version  = "3.5.3";
    category = "ui";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/bf8a357fc756f97951bdb418ab57c3e4.zip";
      name   = "HitScoreVisualizer-3.5.3.zip";
      sha256 = "730f0e93d15eeedc801c3c5b892e26971677481320a3893761ac204af33a65e6";
    };
  }
  {
    name     = "ImageSharp";
    modId    = 257;
    version  = "2.0.0";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/b642fec88b0f84a0643ebd401d08da35.zip";
      name   = "ImageSharp-2.0.0.zip";
      sha256 = "b2bf6d195f25e1298199a389e381ab42f163b284105ae6181259d74f2528301b";
    };
  }
  {
    name     = "Ini Parser";
    modId    = 20;
    version  = "2.5.9";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/5df74ad1c6b120fecdc615dd55f15b88.zip";
      name   = "Ini-Parser-2.5.9.zip";
      sha256 = "b761293bea73ff3cb9998f404594aade617638aba4318203320189baf3449ff1";
    };
  }
  {
    name     = "LeaderboardCore";
    modId    = 243;
    version  = "1.7.0";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/e9303bea2923995c94574c76901fd8b5.zip";
      name   = "LeaderboardCore-1.7.0.zip";
      sha256 = "034b76feba48d4132e9f84601516894ac32df9f96665b4abae20b880aedf015d";
    };
  }
  {
    name     = "LookupID";
    modId    = 231;
    version  = "1.0.1";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/5f5655b91193602c0311b8b6d1b4c71c.zip";
      name   = "LookupID-1.0.1.zip";
      sha256 = "5fc838c9bf3693a8e3728056d95c07c5b0e13f944c1f9f49607f701b58e3d05d";
    };
  }
  {
    name     = "MappingExtensions";
    modId    = 23;
    version  = "1.7.6";
    category = "gameplay";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/5648166a9a37db91d9de834172c02b07.zip";
      name   = "MappingExtensions-1.7.6.zip";
      sha256 = "bf787372bafea3cfa4734667e2405f221ec77a76c2a856cb4cb2e427026241b2";
    };
  }
  {
    name     = "MenuSelector";
    modId    = 365;
    version  = "1.0.0";
    category = "cosmetic";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/bf0d19076968f64be75a4e0d3280031f.zip";
      name   = "MenuSelector-1.0.0.zip";
      sha256 = "41d66f6afea4715f5fd78f64df5030de9a9de99d97120b8061f38b20280f52ac";
    };
  }
  {
    name     = "NoodleExtensions";
    modId    = 193;
    version  = "1.7.18+1.40.3";
    category = "gameplay";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/100df346d07fd0e820460e0eaf32bf9f.zip";
      name   = "NoodleExtensions-1.7.18+1.40.3.zip";
      sha256 = "7596a7ce127226315d11bed2dcf5325b10ba41dd13e99dc691b37cac339fb09e";
    };
  }
  {
    name     = "PlaylistManager";
    modId    = 170;
    version  = "1.7.3";
    category = "essential";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/777baaf710606b7a194ba26c794cc755.zip";
      name   = "PlaylistManager-1.7.3.zip";
      sha256 = "07f2b2ac524dd6e1e9e6ac120839fbaa11156a2ab714f24a5c0035b216ebac52";
    };
  }
  {
    name     = "PracticePlugin";
    modId    = 26;
    version  = "9.1.0";
    category = "practice";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/a64b75e5d39bc0c321a43e9711b75557.zip";
      name   = "PracticePlugin-9.1.0.zip";
      sha256 = "3c1c3e00e992add96c1e345a5319b25366e6c603a267f422e4bbdfe2aa951ec0";
    };
  }
  {
    name     = "protobuf-net";
    modId    = 194;
    version  = "3.0.102";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/1f55ae4b80b747b5f03fa18337ead864.zip";
      name   = "protobuf-net-3.0.102.zip";
      sha256 = "8bf4a361038172eab2c0c2e6737773d6c9a47fc6504a97304a35f697d5166414";
    };
  }
  {
    name     = "RandomSongPlayer";
    modId    = 95;
    version  = "2.0.3";
    category = "gameplay";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/b788ce8145e80d326039e909e52bf488.zip";
      name   = "RandomSongPlayer-2.0.3.zip";
      sha256 = "7d0924e7077ef7b65eb6358526dd29c8c67480179bd394584d3051f471dc3df3";
    };
  }
  {
    name     = "ScoreSaber";
    modId    = 281;
    version  = "3.3.17";
    category = "other";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/06d8fc9416614aae337893c280bc114c.zip";
      name   = "ScoreSaber-3.3.17.zip";
      sha256 = "a9027aa748b0c8226782ff27e3c756db7da836b7f2a96deb47dd24ca1fbd05e1";
    };
  }
  {
    name     = "ScoreSaberSharp";
    modId    = 102;
    version  = "0.1.0";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/8713168c598577ee7c73fa3cf0e26f5c.zip";
      name   = "ScoreSaberSharp-0.1.0.zip";
      sha256 = "7f30be996f8f0e997f2d848e34de1d03ef6dc744ffc32d3fe505881ca22c6cd3";
    };
  }
  {
    name     = "SiraUtil";
    modId    = 130;
    version  = "3.2.1";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/5b90d82d3a9c095747c0ec8cde199d4c.zip";
      name   = "SiraUtil-3.2.1.zip";
      sha256 = "b9c296d1a9ce6df2100f48510573db30242dcac6f58077ff359730c337c39858";
    };
  }
  {
    name     = "SongCore";
    modId    = 58;
    version  = "3.15.3";
    category = "core";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/146b940124681179768738b8ab336103.zip";
      name   = "SongCore-3.15.3.zip";
      sha256 = "50225a4ad33d17952db5b05b30ffe365b3b0c165f265d2cc904865bfbc8a4c3f";
    };
  }
  {
    name     = "SongDetailsCache";
    modId    = 192;
    version  = "1.4.0";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/e1167b64cd3eff7e3651ec2dbbe50d81.zip";
      name   = "SongDetailsCache-1.4.0.zip";
      sha256 = "6ccc816dd40752b46d5e7e1cfb41e5af9d915d1a032be51ce1e52fb154daa28c";
    };
  }
  {
    name     = "System.IO.Compression";
    modId    = 304;
    version  = "4.6.57";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/a4e9e26f61967e56168e08eecb01ab88.zip";
      name   = "System.IO.Compression-4.6.57.zip";
      sha256 = "9067ddaf52c077f38a27ace6180a8134ceaaf1ecba752d08de81b4cc0c13aa43";
    };
  }
  {
    name     = "System.IO.Compression.FileSystem";
    modId    = 303;
    version  = "4.7.3056";
    category = "library";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/e19f6fd395d54de7bfcbbbe3084dea28.zip";
      name   = "System.IO.Compression.FileSystem-4.7.3056.zip";
      sha256 = "1b6f7a33a69980344717a37240ed80b022903a52968d4968f307cf754e3a03f7";
    };
  }
  {
    name     = "Vivify";
    modId    = 378;
    version  = "1.0.5+1.40.3";
    category = "gameplay";
    zip = fetchurl {
      url    = "https://beatmods.com/cdn/mod/1ee5bfec4dbb649141f8ff5d63e2ac61.zip";
      name   = "Vivify-1.0.5+1.40.3.zip";
      sha256 = "4c698d3bb0583da4693f0efdd710c8a3d39cb4c66a379e997389f6d0e5011214";
    };
  }
]
