#!/usr/bin/env python3
"""Resolve wanted-mods.json (top-level mod names) against the BeatMods API
into a fetchurl-ready Nix attrset list, transitively including dependencies.
Output goes to beatsaber-mods.nix.

Run once from the host (not inside a Nix sandbox) when adding a mod or
bumping the target game version, then commit the regenerated
beatsaber-mods.nix.

Why a generated file instead of fetching at eval-time:
- Nix sandboxes builds; fetchurl needs URL+hash known up-front.
- BeatMods' dependency graph for a game version can change server-side
  (mod authors publish updates); resolving at every eval would be flaky
  and non-reproducible.

Deps (run on host): python3 only (stdlib urllib + hashlib).

Usage: generate-mods.py <game-version> <path/to/wanted-mods.json> <path/to/out.nix>
"""
import hashlib
import json
import sys
import urllib.request

API = "https://beatmods.com/api/mods"
CDN = "https://beatmods.com/cdn/mod"
# beatmods.com 403s the default "Python-urllib/x.y" user agent.
USER_AGENT = "nix-config-beatsaber-mods/1.0 (+https://github.com/)"


def _request(url):
    return urllib.request.Request(url, headers={"User-Agent": USER_AGENT})


def fetch_json(url):
    with urllib.request.urlopen(_request(url)) as resp:
        return json.load(resp)


def sha256_of(url):
    h = hashlib.sha256()
    with urllib.request.urlopen(_request(url)) as resp:
        while True:
            chunk = resp.read(1 << 20)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def main():
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <game-version> <wanted-mods.json> <out.nix>", file=sys.stderr)
        sys.exit(2)
    game_version, wanted_path, out_path = sys.argv[1:4]

    with open(wanted_path) as f:
        wanted = json.load(f)

    data = fetch_json(f"{API}?gameVersion={game_version}&status=verified")
    entries = data.get("mods", [])
    if not entries:
        print(f"error: BeatMods returned no mods for gameVersion={game_version!r}", file=sys.stderr)
        sys.exit(1)

    by_version_id = {e["latest"]["id"]: e for e in entries}
    by_name = {e["mod"]["name"]: e for e in entries}

    missing = [name for name in wanted if name not in by_name]
    if missing:
        print(f"error: mods not found for gameVersion={game_version!r}: {missing}", file=sys.stderr)
        sys.exit(1)

    # BFS over `latest.dependencies` (mod-version IDs), which BeatMods
    # guarantees are all present in this same gameVersion-filtered response.
    resolved = {}
    queue = [by_name[name]["latest"]["id"] for name in wanted]
    while queue:
        vid = queue.pop()
        if vid in resolved:
            continue
        entry = by_version_id.get(vid)
        if entry is None:
            print(f"error: dependency version id {vid} missing from gameVersion={game_version!r} response", file=sys.stderr)
            sys.exit(1)
        resolved[vid] = entry
        queue.extend(entry["latest"]["dependencies"])

    out = [
        "# AUTO-GENERATED by pkgs/beatsaber-mods/generate-mods.py",
        f"# Source: BeatMods API, gameVersion={game_version} ({len(resolved)} mods incl. dependencies)",
        "{ fetchurl }:",
        "[",
    ]
    for entry in sorted(resolved.values(), key=lambda e: e["mod"]["name"].lower()):
        mod, latest = entry["mod"], entry["latest"]
        zip_hash = latest["zipHash"]
        url = f"{CDN}/{zip_hash}.zip"
        print(f"hashing {mod['name']} {latest['modVersion']}...", file=sys.stderr)
        sha256 = sha256_of(url)
        name = f"{mod['name']}-{latest['modVersion']}.zip".replace(" ", "-")
        out += [
            "  {",
            f"    name     = {json.dumps(mod['name'])};",
            f"    modId    = {mod['id']};",
            f"    version  = {json.dumps(latest['modVersion'])};",
            f"    category = {json.dumps(mod.get('category', ''))};",
            "    zip = fetchurl {",
            f"      url    = {json.dumps(url)};",
            f"      name   = {json.dumps(name)};",
            f"      sha256 = {json.dumps(sha256)};",
            "    };",
            "  }",
        ]
    out.append("]")

    with open(out_path, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {out_path}: {len(resolved)} mods", file=sys.stderr)


if __name__ == "__main__":
    main()
