[workspace]
resolver = "2"
members = ["cc-obs-ledger", "cc-obs-query"]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
unwrap_in_result = "deny"
panic = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "deny"
unreachable = "deny"
todo = "deny"
unimplemented = "deny"
get_unwrap = "deny"
