# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, modulesPath
, ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    (modulesPath + "/profiles/qemu-guest.nix")
    # (modulesPath + "/virtualisation/qemu-vm.nix")
  ];

  # VM variant configuration is now handled by the base module
  # See modules/base/vm-variant.nix
  vmVariantSettings = {
    memorySize = 4096;
    cores = 8;
    diskSize = 65536; # 64GB
    # This host uses GRUB, so don't auto-configure systemd-boot
    configureBootLoader = false;
  };

  boot = {
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    extraModprobeConfig = ''
      softdep drm pre: vfio-pci
      softdep mpt3sas pre: vfio-pci
    '';

    initrd = {
      availableKernelModules = [ "xhci_pci" "nvme" "ahci" "uas" "usbhid" "usb_storage" "sd_mod" "sr_mod" "virtio_blk" "ehci_pci" "cryptd" "virtio_pci" ];
      kernelModules = [ "dm-snapshot" "vfio-pci" "vfio" "vfio_iommu_type1" ];
    };
  };

  # networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp12s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f0.useDHCP = true;
  # networking.interfaces.enp1s0f1.useDHCP = true;
  # networking.interfaces.br0.useDHCP = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
